config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'home/about',as: 'about'
  get 'terms', to: 'home#terms'
  get 'privacy', to: 'home#privacy'
  # 管理者関連
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    get 'dashboard', :to => 'dashboard#index'
    get 'dashboard/login', :to => 'admins/sessions#new'
    post 'dashboard/login', :to => 'admins/sessions#create'
    delete 'dashboard/logout', :to => 'admins/sessions#destroy'
    post 'dashboard/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  # user関連
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  # userのサインアップなど

  devise_scope :user do
    get 'signup', :to => 'users/registrations#new'
    get 'login', :to => 'users/sessions#new'
    delete 'logout', :to => 'users/sessions#destroy'
    #ゲストログイン
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  # URLは指定のパスにしたい,ファイル構成も指定のパスにしたいとき、namescope
  # URLは指定のパスにしたい,ファイル構成変えたくないとき、scope

  namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show,:new]
    resources :products, except: [:show] do
      collection do
        get  'import/csv', :to => 'products#import'
        post 'import/csv', :to => 'products#import_csv'
        get  'import/csv_download', :to => 'products#download_csv'
        get  '/favorite', :to => 'products#favorite_users'
      end
    end
    resources :orders, only: [:index,:show]
  end

  # 商品関連
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
    member do
      get :favorite
    end
  end

  #検索
  get '/search', to: 'searches#search'


  # userに関するページ

  resource :users, only: [:show] do
    collection do
      get 'cart', :to => 'shopping_carts#index'
      post 'cart/create', :to => 'shopping_carts#create'
      #商品１個ずつ削除
      delete 'cart/:id', :to => 'shopping_carts#delete_item', as: 'cart_delete'
      #カートを空にする
      delete 'deletecart', :to => 'shopping_carts#all_destroy'
      #購入する
      delete 'cart', :to => 'shopping_carts#destroy'
      delete 'guestcart', :to => 'shopping_carts#guest_destroy'
      #アカウント情報の変更
      get 'mypage/show', :to => 'users#show'
      #マイページ
      get 'mypage', :to => 'users#mypage'
      #パスワード
      get 'mypage/edit_password', :to =>'users#edit_password'
      put 'mypage/password', :to => 'users#update_password'
      #お気に入り
      get  'mypage/favorite', :to => 'users#favorite'
      #退会
      delete 'mypage/delete', :to => 'users#destroy'
      #購入履歴 indexとshow
      get 'mypage/purchases', :to => 'purchases#index',:as => 'mypage_purchases'
      get 'mypage/purchases/:num', :to => 'purchases#show', :as => 'mypage_purchase'
      #クレジットカード登録
      get    'mypage/register_card',     :to => 'users#register_card'
      post   'mypage/token',             :to => 'users#token'
    end
  end

  #お問い合わせ

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: :index
  before_action :set_category, only: %w[edit update destroy]
  layout 'dashboard/dashboard'

  def index
    @categories = Category.display_list(params[:page])
    @category = Category.new

  end

  def create
    category = Category.new(category_params)
    category.save
    redirect_to dashboard_categories_path

  end

  def edit

  end

  def update
    @category.update(category_params)
    @category.save
    redirect_to dashboard_categories_path

  end

  def destroy
    @category.destroy
    redirect_to dashboard_categories_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'

  def index
    if params[:code].present?
      #検索した受注番号がある商品
      @orders = ShoppingCart.search_bought_carts_by_ids(params[:code]).page(params[:page]).per(15)
    else
      #購入フラグがtrueの商品
      @orders = ShoppingCart.bought_carts.page(params[:page]).per(15)
    end
  end

  def show
    @cart = ShoppingCart.find(params[:id])
    @cart_items = ShoppingCartItem.user_cart_items(@cart.id)
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %w[show edit update destroy]
  layout 'dashboard/dashboard'

  def index
    @sorted = ''
    @sort_list = Product.sort_list

    if params[:sort].present?
      @sorted = params[:sort]
    end

    if params[:keyword].present?
      keyword = params[:keyword].strip
      @total_count = Product.search_for_id_and_name(keyword).count
      @products = Product.search_for_id_and_name(keyword).display_list(params[:pages])
    else
      @total_count = Product.count
      @products = Product.sort_order(@sorted).display_list(params[:page])
    end
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    tag_list = params[:product][:tag_name].split(',')

    if @product.save
      @product.save_tags(tag_list)
      redirect_to dashboard_products_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    @product.update(product_params)
    redirect_to dashboard_products_path
  end

  def destroy
    @product.destroy
    redirect_to dashboard_products_path
  end

  #表示用、get
  def import
  end

  #import、post
  def import_csv
    Product.import_csv(params[:file])
    redirect_to import_csv_dashboard_products_path
  end

  #雛形ダウンロード用
  def download_csv
    send_file(
      "#{Rails.root}/public/csv/products.csv",
      filename: 'products.csv',
      type: :csv
    )
  end

  def favorite_users
    @products = Product.all

  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
    # おすすめ商品かどうかを判定するフラグ
    def product_params
      params.require(:product).permit(:name, :description, :price, :recommended_flag, :carriage_flag, :soldout_flag, :category_id, :image)
    end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'
  before_action :ensure_guest_user, only: [:destroy]

  def index
    if params[:keyword].present?
      @keyword = params[:keyword].strip
      @users = User.search_information(@keyword).display_list(params[:pages])
    else
      @keyword = ''
      @users = User.display_list(params[:pages])
    end
  end

  # ユーザーの退会処理
  def destroy
    user = User.find(params[:id])
    #switch_flgメソッドは、与えられた引数によってtrueまたはfalseを返す。
    deleted_flg = User.switch_flg(user.deleted_flg)
    user.update(deleted_flg: deleted_flg)
    redirect_to dashboard_users_path
  end
  
  private
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to root_path , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'

  def index
  end
end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/views/layouts/dashboard/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-light.shadow-sm.header-container
  %a.navbar-brand{:href => "/products"} Ako-shop
  = link_to "HOMEへ",products_path, class: "btn btn-secondary btn-sm mr-2" 
  = link_to destroy_admin_session_path , method: :delete , class: "btn btn-dark btn-sm" do
    管理者ログアウト

app/views/layouts/dashboard/_sidebar.html.haml
.side-admin
  .container.ml-3
    %h2.side-admin-main 受注管理
    .d-flex.flex-column
      %label.sidebar-category-label
        = link_to "受注一覧", dashboard_orders_path, class:"sidebar-category-label_link"
    %h2.side-admin-main 商品管理
    .d-flex.flex-column
      %label.sidebar-category-label
        = link_to "商品一覧", dashboard_products_path, class:"sidebar-category-label_link"
      %label.sidebar-category-label
        = link_to "商品新規作成", new_dashboard_product_path, class:"sidebar-category-label_link"
      %label.sidebar-category-label
        = link_to "カテゴリ管理", dashboard_categories_path, class:"sidebar-category-label_link"
      %label.sidebar-category-label
        = link_to "CSV一括登録", import_csv_dashboard_products_path, class:"sidebar-category-label_link"
    %h2.side-admin-main 顧客管理
    .d-flex.flex-column
      %label.sidebar-category-label
        = link_to "顧客一覧", dashboard_users_path ,class:"sidebar-category-label_link"
    %h2.side-admin-main その他
    .d-flex.flex-column
      %label.sidebar-category-label 新着情報管理
      %label.sidebar-category-label
        = link_to "お気に入り商品管理", favorite_dashboard_products_path ,class:"sidebar-category-label_link"

app/views/layouts/dashboard/dashboard.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Ako shop
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/dashboard/header'
    .row
      .col-md-4.mt-3
        = render partial: 'layouts/dashboard/sidebar'
      .col
        %main.py-4.mb-5
          = render 'layouts/flash'
          = yield