config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'home/about',as: 'about'
  get 'terms', to: 'home#terms'
  get 'privacy', to: 'home#privacy'
  # 管理者関連
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    get 'dashboard', :to => 'dashboard#index'
    get 'dashboard/login', :to => 'admins/sessions#new'
    post 'dashboard/login', :to => 'admins/sessions#create'
    delete 'dashboard/logout', :to => 'admins/sessions#destroy'
    post 'dashboard/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  # user関連
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  # userのサインアップなど

  devise_scope :user do
    get 'signup', :to => 'users/registrations#new'
    get 'login', :to => 'users/sessions#new'
    delete 'logout', :to => 'users/sessions#destroy'
    #ゲストログイン
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  # URLは指定のパスにしたい,ファイル構成も指定のパスにしたいとき、namescope
  # URLは指定のパスにしたい,ファイル構成変えたくないとき、scope

  namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show,:new]
    resources :products, except: [:show] do
      collection do
        get  'import/csv', :to => 'products#import'
        post 'import/csv', :to => 'products#import_csv'
        get  'import/csv_download', :to => 'products#download_csv'
        get  '/favorite', :to => 'products#favorite_users'
      end
    end
    resources :orders, only: [:index,:show]
  end

  # 商品関連
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
    member do
      get :favorite
    end
  end

  #検索
  get '/search', to: 'searches#search'


  # userに関するページ

  resource :users, only: [:show] do
    collection do
      get 'cart', :to => 'shopping_carts#index'
      post 'cart/create', :to => 'shopping_carts#create'
      #商品１個ずつ削除
      delete 'cart/:id', :to => 'shopping_carts#delete_item', as: 'cart_delete'
      #カートを空にする
      delete 'deletecart', :to => 'shopping_carts#all_destroy'
      #購入する
      delete 'cart', :to => 'shopping_carts#destroy'
      delete 'guestcart', :to => 'shopping_carts#guest_destroy'
      #アカウント情報の変更
      get 'mypage/show', :to => 'users#show'
      #マイページ
      get 'mypage', :to => 'users#mypage'
      #パスワード
      get 'mypage/edit_password', :to =>'users#edit_password'
      put 'mypage/password', :to => 'users#update_password'
      #お気に入り
      get  'mypage/favorite', :to => 'users#favorite'
      #退会
      delete 'mypage/delete', :to => 'users#destroy'
      #購入履歴 indexとshow
      get 'mypage/purchases', :to => 'purchases#index',:as => 'mypage_purchases'
      get 'mypage/purchases/:num', :to => 'purchases#show', :as => 'mypage_purchase'
      #クレジットカード登録
      get    'mypage/register_card',     :to => 'users#register_card'
      post   'mypage/token',             :to => 'users#token'
    end
  end

  #お問い合わせ

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  acts_as_shopping_cart

  # &.lastにより、配列の最後の値を取り出して user_cartに代入してカートの状態を返す
  scope :set_user_cart, -> (user) { user_cart = where(user_id: user.id, buy_flag: false)&.last
    user_cart.nil? ? ShoppingCart.create(user_id: user.id) : user_cart}

  def tax_pct
    0
  end

  # 購入フラグがtrueのものを
  scope :bought_carts, -> { where(buy_flag: true) }

  #受注番号検索
  scope :search_carts_by_ids, -> (ids) { where('id::text LIKE ?', "%#{ids}%") }
  #検索した受注番号を持ってくる”＋購入フラグがtrue”
  scope :search_bought_carts_by_ids, -> (ids) { bought_carts.search_carts_by_ids(ids) }

  #購入履歴の一覧  購入フラグがtrueのuser_idが一致したuserを持ってくる
  scope :search_carts_by_user, -> (user) { where(user_id: user) }
  scope :search_bought_carts_by_user, -> (user) { bought_carts.search_carts_by_user(user) }

  #送料 acts_as_shopping_cartはもともとUSD（米ドル）。CARRIAGEという定数に日本円で金額を代入し、その金額を100倍した値を引数として渡す
  CARRIAGE = 400
  FREE_SHIPPING = 0

  # shipping_costメソッドではカート内の商品の送料有無carriage_flagの値を取得し、1つでもtrueの商品が含まれていれば合計金額に送料を加算する
  def shipping_cost
    #カートに入っているアイテムのid
    product_ids = ShoppingCartItem.user_cart_item_ids(self.id)
    #carriage_flagの値を取得する
    products_carriage_list = Product.check_products_carriage_list(product_ids)
    # カート内に1つでも送料ありの商品が含まれていれば、定数CARRIAGEの値が合計金額に加算される
    #Money.newの引数はドルの100分の1であるセント単位で整数を渡しているから100倍にする
    products_carriage_list.include?(true) ? Money.new(CARRIAGE * 100) : Money.new(FREE_SHIPPING)
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
before_action :set_cart, only: %i[index create destroy all_destroy guest_destroy]

  def index
    # カートに入っているすべての商品データ
    @user_cart_items = ShoppingCartItem.user_cart_items(@user_cart)
    # user_cart_items カートに入っているすべての商品のデータを返す。
  end

  def show
    @cart = ShoppingCart.find(user_id: current_user)
  end

  def create
    # acts_as_shopping_cartで用意されているaddメソッド
    # to_iは文字列（String）を整数（Integer）に変換するメソッド
    @product = Product.find(product_params[:product_id])
    @user_cart.add(@product, product_params[:price].to_i, product_params[:quantity].to_i)
    redirect_to cart_users_path
  end

  def update

  end

  #カート商品１個ずつ空にする
  def delete_item
    item = ShoppingCartItem.find(params[:id])
    item.destroy
    redirect_to cart_users_path
  end

  #カートの中身を空にする
  def all_destroy
    user_cart_items = ShoppingCartItem.user_cart_items(@user_cart)
    if user_cart_items.destroy_all
      flash[:notice] = 'カート商品を全て削除しました'
      redirect_to cart_users_path
    else
      @user_cart_items = ShoppingCartItem.user_cart_items(@user_cart)
      render :index
    end

  end

  def destroy
    @user_cart.buy_flag = true
    @user_cart.save

    #購入時に決済できるように
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
                          :customer => current_user.token,
                          :amount => @user_cart.total.to_i,
                          :currency => 'jpy'
                        )

    redirect_to cart_users_path
  end

  def guest_destroy
    @user_cart.buy_flag = true
    @user_cart.save
    redirect_to cart_users_path
  end

  private

  def product_params
    params.permit(:product_id, :price, :quantity)
  end

  def set_cart
    # まだ注文が確定していないカートのデータ
    @user_cart = ShoppingCart.set_user_cart(current_user)
    # set_user_cart まだ注文が確定していないカートのデータを返し、データがなければ新しく作る。
  end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/_purchase_btn.html.haml
-if current_user.name != "guestuser"
  = form_with url: cart_users_path , method: :delete, class: " mt-3" do |f|
    .btn.btn-primary.mx-auto.d-block.mb-3{"data-target" => "#buy-confirm-modal", "data-toggle" => "modal"} 注文画面へ進む
    #buy-confirm-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "staticBackdropLabel", "data-backdrop" => "static", "data-keyboard" => "false", :role => "dialog", :tabindex => "-1"}
      .modal-dialog
        .modal-content
          .modal-header
            %h5#staticBackdropLabel.modal-title 購入を確定しますか？
            %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
          .modal-footer
            %button.btn.favorite-button.border-dark.text-dark{"data-dismiss" => "modal", :type => "button"} 閉じる
            %button.btn.btn-primary.submit-button{:type => "submit"} 購入
    = link_to "ショッピングを続ける", products_path, class: "link d-flex justify-content-center"
-else 
  = form_with url: guestcart_users_path , method: :delete, class: " mt-3" do |f|
    .btn.btn-primary.mx-auto.d-block.mb-3{"data-target" => "#buy-confirm-modal", "data-toggle" => "modal"} 注文画面へ進む
    #buy-confirm-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "staticBackdropLabel", "data-backdrop" => "static", "data-keyboard" => "false", :role => "dialog", :tabindex => "-1"}
      .modal-dialog
        .modal-content
          .modal-header
            %h5#staticBackdropLabel.modal-title 購入を確定しますか？(guestの方)
            %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
          .modal-footer
            %button.btn.favorite-button.border-dark.text-dark{"data-dismiss" => "modal", :type => "button"} 閉じる
            %button.btn.btn-primary.submit-button{:type => "submit"} 購入
    = link_to "ショッピングを続ける", products_path, class: "link d-flex justify-content-center"

app/views/shopping_carts/index.html.haml
.col-md-8.offset-md-1.content
  %h2 カートに入っているアイテム
  - if @user_cart_items.exists?
    = link_to "カートを空にする", deletecart_users_path , method: :delete, class: "btn btn-outline-danger btn-sm"
  %table.table.table-hover.table-inverse
    %thead
      %tr
        %th
        %th アイテム名
        %th 個数
        %th 小計
        %th
        %th{:colspan => "2"}
    %tbody
      - @user_cart_items.each do |user_cart_item|
        - product = Product.find(user_cart_item.item_id)
        %tr
          %td
            = link_to product_path(product) do
              - if product.image.attached?
                = image_tag product.image, :size => '130x130'
              - else
                = image_tag "salt.png", :size => '130x130'
          %td= product.name
          %th= user_cart_item.quantity
          %th
            ￥#{(user_cart_item.price_cents * user_cart_item.quantity).to_s(:delimited)}
          %th= link_to "削除", cart_delete_users_path(user_cart_item.id), method: :delete, class: "btn btn-outline-danger btn-sm"
  %hr/
  .offset-8.col-4
    .row
      .col-6
        %h2 小計
      .col-6
        %h2
          ￥#{((@user_cart.total - @user_cart.shipping_cost).fractional / 100).to_s(:delimited)}
    .row
      .col-6
        %h2 送料
      .col-6
        %h2
          ￥#{@user_cart.shipping_cost.fractional / 100}
    .row
      .col-6
        %h2 合計
      .col-6
        %h2
          ￥#{(@user_cart.total.fractional / 100 ).to_s(:delimited)}
      .col-12.d-flex.justify-content-end
        表示価格は税込みです
  = render 'purchase_btn'