config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'home/about',as: 'about'
  get 'terms', to: 'home#terms'
  get 'privacy', to: 'home#privacy'
  # 管理者関連
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    get 'dashboard', :to => 'dashboard#index'
    get 'dashboard/login', :to => 'admins/sessions#new'
    post 'dashboard/login', :to => 'admins/sessions#create'
    delete 'dashboard/logout', :to => 'admins/sessions#destroy'
    post 'dashboard/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  # user関連
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  # userのサインアップなど

  devise_scope :user do
    get 'signup', :to => 'users/registrations#new'
    get 'login', :to => 'users/sessions#new'
    delete 'logout', :to => 'users/sessions#destroy'
    #ゲストログイン
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  # URLは指定のパスにしたい,ファイル構成も指定のパスにしたいとき、namescope
  # URLは指定のパスにしたい,ファイル構成変えたくないとき、scope

  namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show,:new]
    resources :products, except: [:show] do
      collection do
        get  'import/csv', :to => 'products#import'
        post 'import/csv', :to => 'products#import_csv'
        get  'import/csv_download', :to => 'products#download_csv'
        get  '/favorite', :to => 'products#favorite_users'
      end
    end
    resources :orders, only: [:index,:show]
  end

  # 商品関連
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
    member do
      get :favorite
    end
  end

  #検索
  get '/search', to: 'searches#search'


  # userに関するページ

  resource :users, only: [:show] do
    collection do
      get 'cart', :to => 'shopping_carts#index'
      post 'cart/create', :to => 'shopping_carts#create'
      #商品１個ずつ削除
      delete 'cart/:id', :to => 'shopping_carts#delete_item', as: 'cart_delete'
      #カートを空にする
      delete 'deletecart', :to => 'shopping_carts#all_destroy'
      #購入する
      delete 'cart', :to => 'shopping_carts#destroy'
      delete 'guestcart', :to => 'shopping_carts#guest_destroy'
      #アカウント情報の変更
      get 'mypage/show', :to => 'users#show'
      #マイページ
      get 'mypage', :to => 'users#mypage'
      #パスワード
      get 'mypage/edit_password', :to =>'users#edit_password'
      put 'mypage/password', :to => 'users#update_password'
      #お気に入り
      get  'mypage/favorite', :to => 'users#favorite'
      #退会
      delete 'mypage/delete', :to => 'users#destroy'
      #購入履歴 indexとshow
      get 'mypage/purchases', :to => 'purchases#index',:as => 'mypage_purchases'
      get 'mypage/purchases/:num', :to => 'purchases#show', :as => 'mypage_purchase'
      #クレジットカード登録
      get    'mypage/register_card',     :to => 'users#register_card'
      post   'mypage/token',             :to => 'users#token'
    end
  end

  #お問い合わせ

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy

  #タグ
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags

  acts_as_likeable
  has_one_attached :image

  # カテゴリによる絞り込み
  # モジュールの読み込み(product.rb& category.rb,user.rb)

  # PER = 15
  # scope :display_list, -> (page) { page(page).per(PER) }
  extend DisplayList

  # scope :category_products, -> (category, page) {
  #   where(category_id: category).page(page).per(PER)
  # }

  # scope :sort_products, -> (sort_order, page) {
  #   where(category_id: sort_order[:sort_category]).order(sort_order[:sort]).
  #   page(page).per(PER)
  # }
  scope :on_category, -> (category) { where(category_id: category) }
  scope :sort_order, -> (order) { order(order) }

  scope :category_products, -> (category, page) {
    on_category(category).
    display_list(page)
  }

  scope :sort_products, -> (sort_order, page) {
    on_category(sort_order[:sort_category]).
    sort_order(sort_order[:sort]).
    display_list(page)
  }

  scope :sort_list, -> {
    {
      'おすすめ順' => '',
      '新着順' => 'updated_at desc',
      '価格が安い順' => 'price asc',
      '価格が高い順' => 'price desc'

    }
  }

  # postgresの時は::textを入れる
  scope :search_for_id_and_name, -> (keyword) {
    where('name::text LIKE ?', "%#{keyword}%").
    or(where('id::text LIKE ?', "%#{keyword}%"))
  }

  #おすすめ商品 flug= trueの商品を取ってくる
  scope :recommend_products, -> (number) { where(recommended_flag: true).take(number) }
  #送料の有無を判定するフラグを取ってくる
  scope :check_products_carriage_list, -> (product_ids) { where(id: product_ids).pluck(:carriage_flag)}

  def self.import_csv(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      product = find_by(id: row['id']) || new
      # CSVからデータを取得し、設定する
      product.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      product.save!(validate: false)
    end
  end

  #レビュー(idがあるのだけとってくる)
  def reviews_with_id
    reviews.reviews_with_id
  end

#検索
  def self.search_for(content, method)
    if method == 'patical'
      Product.where('name LIKE ?', '%'+content+'%')
    end
  end

  #タグ
  def save_tags(saveitem_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - saveitem_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = saveitem_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      item_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << item_tag
    end
  end

  private
    def self.updatable_attributes
      [:name, :description, :price, :recommended_flag, :carriage_flag, :soldout_flag]
    end
    #名前、商品説明、料金、おすすめフラグ、送料有無フラグ
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: :index
  before_action :set_category, only: %w[edit update destroy]
  layout 'dashboard/dashboard'

  def index
    @categories = Category.display_list(params[:page])
    @category = Category.new

  end

  def create
    category = Category.new(category_params)
    category.save
    redirect_to dashboard_categories_path

  end

  def edit

  end

  def update
    @category.update(category_params)
    @category.save
    redirect_to dashboard_categories_path

  end

  def destroy
    @category.destroy
    redirect_to dashboard_categories_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'

  def index
    if params[:code].present?
      #検索した受注番号がある商品
      @orders = ShoppingCart.search_bought_carts_by_ids(params[:code]).page(params[:page]).per(15)
    else
      #購入フラグがtrueの商品
      @orders = ShoppingCart.bought_carts.page(params[:page]).per(15)
    end
  end

  def show
    @cart = ShoppingCart.find(params[:id])
    @cart_items = ShoppingCartItem.user_cart_items(@cart.id)
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %w[show edit update destroy]
  layout 'dashboard/dashboard'

  def index
    @sorted = ''
    @sort_list = Product.sort_list

    if params[:sort].present?
      @sorted = params[:sort]
    end

    if params[:keyword].present?
      keyword = params[:keyword].strip
      @total_count = Product.search_for_id_and_name(keyword).count
      @products = Product.search_for_id_and_name(keyword).display_list(params[:pages])
    else
      @total_count = Product.count
      @products = Product.sort_order(@sorted).display_list(params[:page])
    end
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    tag_list = params[:product][:tag_name].split(',')

    if @product.save
      @product.save_tags(tag_list)
      redirect_to dashboard_products_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    @product.update(product_params)
    redirect_to dashboard_products_path
  end

  def destroy
    @product.destroy
    redirect_to dashboard_products_path
  end

  #表示用、get
  def import
  end

  #import、post
  def import_csv
    Product.import_csv(params[:file])
    redirect_to import_csv_dashboard_products_path
  end

  #雛形ダウンロード用
  def download_csv
    send_file(
      "#{Rails.root}/public/csv/products.csv",
      filename: 'products.csv',
      type: :csv
    )
  end

  def favorite_users
    @products = Product.all

  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
    # おすすめ商品かどうかを判定するフラグ
    def product_params
      params.require(:product).permit(:name, :description, :price, :recommended_flag, :carriage_flag, :soldout_flag, :category_id, :image)
    end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'
  before_action :ensure_guest_user, only: [:destroy]

  def index
    if params[:keyword].present?
      @keyword = params[:keyword].strip
      @users = User.search_information(@keyword).display_list(params[:pages])
    else
      @keyword = ''
      @users = User.display_list(params[:pages])
    end
  end

  # ユーザーの退会処理
  def destroy
    user = User.find(params[:id])
    #switch_flgメソッドは、与えられた引数によってtrueまたはfalseを返す。
    deleted_flg = User.switch_flg(user.deleted_flg)
    user.update(deleted_flg: deleted_flg)
    redirect_to dashboard_users_path
  end
  
  private
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to root_path , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'

  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :favorite]
  
  RECOMMEND_PRODUCTS_PER_PAGE = 6

  def index

    if sort_params.present?
      @category = Category.request_category(sort_params[:sort_category])
      @products = Product.sort_products(sort_params, params[:page])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end
    #1 sort_paramsが存在する（並び替えをしたとき）
    #2 sort_paramsは存在しないが、params[:category]が存在する（カテゴリを選択したとき）
    #3 どちらも存在しない（indexページにアクセスしたとき）

    @categories = Category.all
    @sort_list = Product.sort_list

    @rank_products = Product.find(ShoppingCartItem.group(:item_id).order('count(item_id) desc').limit(5).pluck(:item_id))
  end

  def show
    @reviews = @product.reviews_with_id
    @review = @reviews.new
    @recommend_products = Product.recommend_products(RECOMMEND_PRODUCTS_PER_PAGE)
  end

  
  def favorite
    current_user.toggle_like!(@product)
    # redirect_to product_url @product

  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id)
    end

    # def category_params
    #   params[:category].present? ? params[:category] : "none"
    # end

    def sort_params
      params.permit(:sort, :sort_category)
    end
end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/products/edit.html.haml
.w-60.content
  %h1 商品編集
  %hr/
  = form_with model: @product, url: dashboard_product_path, local: true do |f|
    .form-inline.mt-4.mb-4.row
      = f.label :name, "商品名", class: "col-2 d-flex justify-content-start"
      = f.text_field :name, class: "form-control col-8"
    .form-inline.mt-4.mb-4.row
      = f.label :description, "商品説明", class: "col-2 d-flex justify-content-start"
      = f.text_area :description, class: "form-control col-8"
    .form-inline.mt-4.mb-4.row
      = f.label :price, "価格", class: "col-2 d-flex justify-content-start"
      = f.text_field :price, class: "form-control col-8"
    .form-inline.mt-4.mb-4.row
      = f.label :category_id, "カテゴリ", class: "col-2 d-flex justify-content-start"
      = f.select :category_id, Category.all.map { |category| [category.name, category.id] }, {}, class: "form-control"
    .form-inline.mt-4.mb-4.row
      = f.label "画像", class: "col-2 d-flex justify-content-start"
      - if @product.image.attached?
        = image_tag @product.image, id: "product-image-preview", class: "img-fluid w-25"
      - else
        %img#product-image-preview{:src => "#"}/
      .d-flex.flex-column.ml-2
        %small.mb-3
          600px×600px推奨。
          %br>/
          画像をアップロードする。
        = f.label "画像を選択", for: "product_image", class: "btn btn-outline-dark btn-sm"
        = f.file_field :image, { onChange: "javascript: handleImage(this.files);", style: "display: none;"}
    .form-inline.mt-4.mb-4.row
      = f.label :recommended_flag, "オススメする",  class: "col-2 d-flex justify-content-start"
      = f.check_box :recommended_flag, class: "check-box"
    .form-inline.mt-4.mb-4.row
      = f.label :carriage_flag, "送料", class: "col-2 d-flex justify-content-start"
      = f.check_box :carriage_flag, class: "check-box"
    .form-inline.mt-4.mb-4.row
      = f.label "売り切れ？", class: "col-2 d-flex justify-content-start"
      = f.check_box :soldout_flag, class: "check-box"
    = f.submit "更新", class: "w-25 btn btn btn-success d-block mx-auto"
  .mt-4= link_to "商品一覧に戻る", dashboard_products_path, class: "d-flex justify-content-center"
= javascript_pack_tag 'edit'

app/views/dashboard/products/favorite_users.html.haml
.container.d-flex.justify-content-center.mt-3
  .w-75.content
    %h2 予約商品
    %hr/
    %table.table.table-responsive.mt-5
      %thead
        %tr
          %th{:scope => "col"} 商品
          %th{:scope => "col"} id
          %th{:scope => "col"} name
          %th{:scope => "col"} mail
          %th{:scope => "col"} tel
      %tbody
        - @products.each do |product|
          - product.likers(User).each do |user|
            %tr
              %td
                - if product.image.attached?
                  = image_tag product.image, :size => '100x100'
                - else
                  = image_tag "salt.png", :size => '100x100'
              %td= user.id
              %td= user.name
              %td= user.email
              %td= user.phone
    %hr/

app/views/dashboard/products/import.html.haml
.w-75.content
  %h1 商品CSV登録
  = form_with model: @product, url: import_csv_dashboard_products_path, local: true do |f|
    .d-flex.flex-column
      .d-flex.flex-row
        = f.label "CSVファイルを選択", for: "file" ,class: "btn  mr-3 mb-0"
        = f.file_field :file
        = f.submit "一括登録", class: "btn btn-primary"
    %small#product-import-csv-filename
  .d-flex.justify-content-between.mt-3
    %h4.d-flex.align-self-center.mt-1.mb-0 CSVファイルフォーマット
    = link_to "雛形ファイルダウンロード", import_csv_download_dashboard_products_path, class: "btn csv-button"
  %hr/
  .row
    %label.col-3 商品ID
    %span.col-9 新規登録の場合は空にしてください。既存の商品を更新する場合は、商品IDを指定してください。
    %label.col-3 商品名
    %span.col-9
    %label.col-3 商品説明
    %span.col-9
    %label.col-3 価格
    %span.col-9
    %label.col-3 カテゴリID
    %span.col-9
    %label.col-3 オススメ商品フラグ
    %span.col-9
    %label.col-3 送料フラグ
    %span.col-9
  %hr/

app/views/dashboard/products/index.html.haml
.content
  %h1 商品管理
  = form_with url: dashboard_products_path, method: :get, local: true, class: "form-inline" do |f|
    並び替え
    - if @sorted.present?
      = f.select :sort, @sort_list, { selected: @sorted }, { onChange: "javascript: this.form.submit();", class: "form-inline ml-5 form-control" }
    - else
      = f.select :sort, @sort_list, {}, { onChange: "javascript: this.form.submit();", class: "form-inline ml-5 form-control" }
  .mt-2
    .w-75
      = form_with url: dashboard_products_path, method: :get, local: true do |f|
        .d-flex.flex-inline.form-group
          .d-flex.align-items-center
            商品ID・商品名
          = f.text_area :keyword, class: "form-control ml-2 w-50"
        = f.submit "検索", class: "btn btn btn-secondary d-block mx-auto"
    .d-flex.justify-content-between.w-75.mt-4
      %h3
        合計#{@total_count}件
      = link_to "新規作成", new_dashboard_product_path, class: "btn btn-primary"
    %table.table.table-responsive.mt-5
      %thead
        %tr
          %th{:scope => "col"} ID
          %th{:scope => "col"} 画像
          %th{:scope => "col"} 商品名
          %th{:scope => "col"} 価格
          %th{:scope => "col"} カテゴリ名
          %th{:scope => "col"} タグ
          %th{:scope => "col"}
          %th{:scope => "col"}
      %tbody
        - @products.each do |product|
          %tr
            %th{:scope => "row"}
              = product.id
            %td
              - if product.image.attached?
                = image_tag product.image, :size => '100x100'
              - else
                = image_tag "salt.png", :size => '100x100'
            %td= product.name
            %td= product.price.to_s(:delimited)
            %td= product.category.name
            %td
              - product.tags.each do |tag|
                %li{:style => "list-style: none;"}
                  = link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect")
            %td
              = link_to "編集", edit_dashboard_product_path(product), class: " btn btn-outline-success  btn-sm"
            %td
              = link_to "削除", dashboard_product_path(product), method: :delete, class: "btn btn-outline-danger btn-sm"
  = paginate @products

app/views/dashboard/products/new.html.haml
.w-60.content
  %h1 商品登録
  %hr/
  = form_with model: @product, url: dashboard_products_path, local: true do |f|
    .form-inline.mt-4.mb-4.row
      = f.label "商品名", class: "col-2 d-flex justify-content-start"
      = f.text_field :name, class: "form-control col-8"
    .form-inline.mt-4.mb-4.row
      = f.label "商品説明", class: "col-2 d-flex justify-content-start"
      = f.text_area :description, class: "form-control col-8"
    .form-inline.mt-4.mb-4.row
      = f.label "価格", class: "col-2 d-flex justify-content-start"
      = f.number_field :price, class: "form-control col-8"
    .form-inline.mt-4.mb-4.row
      = f.label "カテゴリ", class: "col-2 d-flex justify-content-start"
      = f.collection_select(:category_id, @categories, :id, :name)
    .form-inline.mt-4.mb-4.row
      = f.label "画像", class: "col-2 d-flex justify-content-start"
      - if @product.image.attached?
        = image_tag @product.image, id: "product-image-preview", class: "img-fluid w-25"
      - else
        %img#product-image-preview{:src => "#"}/
      .d-flex.flex-column.ml-2
        %small.mb-3
          600px×600px推奨。
          %br>/
          画像をアップロードする。
        = f.label "画像を選択", for: "product_image", class: "btn btn-outline-dark btn-sm"
        = f.file_field :image, { onChange: "javascript: handleImage(this.files);", style: "display: none;"}
    .form-inline.mt-4.mb-4.row
      = f.label "Tag", class: "col-2 d-flex justify-content-start"
      = f.text_field :tag_name, class: 'form-control col-8' ,placeholder: "複数登録は ,で区切ってください"
    .form-inline.mt-4.mb-4.row
      = f.label "オススメする", class: "col-2 d-flex justify-content-start"
      = f.check_box :recommended_flag, class: "check-box"
    .form-inline.mt-4.mb-4.row
      = f.label "送料", class: "col-2 d-flex justify-content-start"
      = f.check_box :carriage_flag, class: "check-box"
    .form-inline.mt-4.mb-4.row
      = f.label "売り切れ？", class: "col-2 d-flex justify-content-start"
      = f.check_box :soldout_flag, class: "check-box"
    = f.submit "商品を登録", class:"btn btn-primary d-block mx-auto"
  .mt-4= link_to "商品一覧に戻る", dashboard_products_path ,class: "d-flex justify-content-center"
= javascript_pack_tag 'new'