config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'
  get 'home/about',as: 'about'
  get 'terms', to: 'home#terms'
  get 'privacy', to: 'home#privacy'
  # 管理者関連
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    get 'dashboard', :to => 'dashboard#index'
    get 'dashboard/login', :to => 'admins/sessions#new'
    post 'dashboard/login', :to => 'admins/sessions#create'
    delete 'dashboard/logout', :to => 'admins/sessions#destroy'
    post 'dashboard/guest_sign_in', to: 'admins/sessions#guest_sign_in'
  end

  # user関連
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  # userのサインアップなど

  devise_scope :user do
    get 'signup', :to => 'users/registrations#new'
    get 'login', :to => 'users/sessions#new'
    delete 'logout', :to => 'users/sessions#destroy'
    #ゲストログイン
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  # URLは指定のパスにしたい,ファイル構成も指定のパスにしたいとき、namescope
  # URLは指定のパスにしたい,ファイル構成変えたくないとき、scope

  namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :categories, except: [:show,:new]
    resources :products, except: [:show] do
      collection do
        get  'import/csv', :to => 'products#import'
        post 'import/csv', :to => 'products#import_csv'
        get  'import/csv_download', :to => 'products#download_csv'
        get  '/favorite', :to => 'products#favorite_users'
      end
    end
    resources :orders, only: [:index,:show]
  end

  # 商品関連
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:index, :create]
    member do
      get :favorite
    end
  end

  #検索
  get '/search', to: 'searches#search'


  # userに関するページ

  resource :users, only: [:show] do
    collection do
      get 'cart', :to => 'shopping_carts#index'
      post 'cart/create', :to => 'shopping_carts#create'
      #商品１個ずつ削除
      delete 'cart/:id', :to => 'shopping_carts#delete_item', as: 'cart_delete'
      #カートを空にする
      delete 'deletecart', :to => 'shopping_carts#all_destroy'
      #購入する
      delete 'cart', :to => 'shopping_carts#destroy'
      delete 'guestcart', :to => 'shopping_carts#guest_destroy'
      #アカウント情報の変更
      get 'mypage/show', :to => 'users#show'
      #マイページ
      get 'mypage', :to => 'users#mypage'
      #パスワード
      get 'mypage/edit_password', :to =>'users#edit_password'
      put 'mypage/password', :to => 'users#update_password'
      #お気に入り
      get  'mypage/favorite', :to => 'users#favorite'
      #退会
      delete 'mypage/delete', :to => 'users#destroy'
      #購入履歴 indexとshow
      get 'mypage/purchases', :to => 'purchases#index',:as => 'mypage_purchases'
      get 'mypage/purchases/:num', :to => 'purchases#show', :as => 'mypage_purchase'
      #クレジットカード登録
      get    'mypage/register_card',     :to => 'users#register_card'
      post   'mypage/token',             :to => 'users#token'
    end
  end

  #お問い合わせ

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews, dependent: :destroy

  #タグ
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags

  acts_as_likeable
  has_one_attached :image

  # カテゴリによる絞り込み
  # モジュールの読み込み(product.rb& category.rb,user.rb)

  # PER = 15
  # scope :display_list, -> (page) { page(page).per(PER) }
  extend DisplayList

  # scope :category_products, -> (category, page) {
  #   where(category_id: category).page(page).per(PER)
  # }

  # scope :sort_products, -> (sort_order, page) {
  #   where(category_id: sort_order[:sort_category]).order(sort_order[:sort]).
  #   page(page).per(PER)
  # }
  scope :on_category, -> (category) { where(category_id: category) }
  scope :sort_order, -> (order) { order(order) }

  scope :category_products, -> (category, page) {
    on_category(category).
    display_list(page)
  }

  scope :sort_products, -> (sort_order, page) {
    on_category(sort_order[:sort_category]).
    sort_order(sort_order[:sort]).
    display_list(page)
  }

  scope :sort_list, -> {
    {
      'おすすめ順' => '',
      '新着順' => 'updated_at desc',
      '価格が安い順' => 'price asc',
      '価格が高い順' => 'price desc'

    }
  }

  # postgresの時は::textを入れる
  scope :search_for_id_and_name, -> (keyword) {
    where('name::text LIKE ?', "%#{keyword}%").
    or(where('id::text LIKE ?', "%#{keyword}%"))
  }

  #おすすめ商品 flug= trueの商品を取ってくる
  scope :recommend_products, -> (number) { where(recommended_flag: true).take(number) }
  #送料の有無を判定するフラグを取ってくる
  scope :check_products_carriage_list, -> (product_ids) { where(id: product_ids).pluck(:carriage_flag)}

  def self.import_csv(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      product = find_by(id: row['id']) || new
      # CSVからデータを取得し、設定する
      product.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      product.save!(validate: false)
    end
  end

  #レビュー(idがあるのだけとってくる)
  def reviews_with_id
    reviews.reviews_with_id
  end

#検索
  def self.search_for(content, method)
    if method == 'patical'
      Product.where('name LIKE ?', '%'+content+'%')
    end
  end

  #タグ
  def save_tags(saveitem_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - saveitem_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = saveitem_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name:old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      item_tag = Tag.find_or_create_by(name:new_name)
      # 配列に保存
      self.tags << item_tag
    end
  end

  private
    def self.updatable_attributes
      [:name, :description, :price, :recommended_flag, :carriage_flag, :soldout_flag]
    end
    #名前、商品説明、料金、おすすめフラグ、送料有無フラグ
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %w[show edit update destroy]
  layout 'dashboard/dashboard'

  def index
    @sorted = ''
    @sort_list = Product.sort_list

    if params[:sort].present?
      @sorted = params[:sort]
    end

    if params[:keyword].present?
      keyword = params[:keyword].strip
      @total_count = Product.search_for_id_and_name(keyword).count
      @products = Product.search_for_id_and_name(keyword).display_list(params[:pages])
    else
      @total_count = Product.count
      @products = Product.sort_order(@sorted).display_list(params[:page])
    end
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    tag_list = params[:product][:tag_name].split(',')

    if @product.save
      @product.save_tags(tag_list)
      redirect_to dashboard_products_path
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    @product.update(product_params)
    redirect_to dashboard_products_path
  end

  def destroy
    @product.destroy
    redirect_to dashboard_products_path
  end

  #表示用、get
  def import
  end

  #import、post
  def import_csv
    Product.import_csv(params[:file])
    redirect_to import_csv_dashboard_products_path
  end

  #雛形ダウンロード用
  def download_csv
    send_file(
      "#{Rails.root}/public/csv/products.csv",
      filename: 'products.csv',
      type: :csv
    )
  end

  def favorite_users
    @products = Product.all

  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
    # おすすめ商品かどうかを判定するフラグ
    def product_params
      params.require(:product).permit(:name, :description, :price, :recommended_flag, :carriage_flag, :soldout_flag, :category_id, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :favorite]
  
  RECOMMEND_PRODUCTS_PER_PAGE = 6

  def index

    if sort_params.present?
      @category = Category.request_category(sort_params[:sort_category])
      @products = Product.sort_products(sort_params, params[:page])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end
    #1 sort_paramsが存在する（並び替えをしたとき）
    #2 sort_paramsは存在しないが、params[:category]が存在する（カテゴリを選択したとき）
    #3 どちらも存在しない（indexページにアクセスしたとき）

    @categories = Category.all
    @sort_list = Product.sort_list

    @rank_products = Product.find(ShoppingCartItem.group(:item_id).order('count(item_id) desc').limit(5).pluck(:item_id))
  end

  def show
    @reviews = @product.reviews_with_id
    @review = @reviews.new
    @recommend_products = Product.recommend_products(RECOMMEND_PRODUCTS_PER_PAGE)
  end

  
  def favorite
    current_user.toggle_like!(@product)
    # redirect_to product_url @product

  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id)
    end

    # def category_params
    #   params[:category].present? ? params[:category] : "none"
    # end

    def sort_params
      params.permit(:sort, :sort_category)
    end
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_favorite.html.haml
- if current_user.likes?(product)
  %i.fas.fa-heart{"aria-hidden" => "true", :style => "color: red;"}
  お気に入り解除
- else
  %i.fas.fa-heart{"aria-hidden" => "true"}
  お気に入り追加

app/views/products/_modal.html.haml
.btn.btn-link.d-flex{"data-target" => "#buy-confirm-modal", "data-toggle" => "modal"}
  %p
    %i.fas.fa-exclamation-circle
    送料について
#buy-confirm-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "staticBackdropLabel", "data-backdrop" => "static", "data-keyboard" => "false", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#staticBackdropLabel.modal-title
          %span.mr-5{:style => "color:gray;"}> 全国一律
          ¥400
        %button.close{"aria-label" => "閉じる", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-footer

app/views/products/_product.html.haml
.row.mt-5
  .container
    - if @category.present?
      .category-title
        = @category.name
      = form_with url: products_path, method: :get, local: true, class: "form-inline" do |f|
        = f.hidden_field :sort_category, value: @category.id
        - if @sorted.present?
          = f.select :sort, @sort_list, selected: @sorted, onChange: "javascript: this.form.submit();", class: "form-inline ml-2"
        - else
          = f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();", class: "form-inline ml-2"
  .container.mt-2
    .row
      - @products.each do |product|
        .col-6.col-md-4
          = link_to product_path(product) do
            - if product.image.attached?
              = image_tag product.image, class: "img-thumbnail"
            - else
              = image_tag "salt.png", class: "img-thumbnail"
          .row
            .col-12
              %p.mt-2
                %strong= product.name
                %br/
                %label
                  ¥#{product.price.to_s(:delimited)}
= paginate @products
%hr/
.content
  .container
    %h3.title Ranking
    .row
      - @rank_products.each.with_index(1) do |product, i|
        .col-4.col-md-2.product-box
          %p{:class => "box-step #{way_color(i)}"}= i
          = link_to product_path(product) do
            - if product.image.attached?
              = image_tag product.image,size:'80x80'
            - else
              = image_tag "salt.png", class: "img-thumbnail"
          .row
            .col-12
              %p.product-lavel.mt-2
                = product.name
                %br/
                %label
                  ¥ #{product.price.to_s(:delimited)}

app/views/products/_review.html.haml
.row.w-75
  .offset-1.col-11
    %hr.w-100/
    %h3.float-left カスタマーレビュー
  .offset-1.col-10
    .row
      - @reviews.each do |review|
        .review-rate
          %div{:id => "star-rate-#{review.id}"}
          :javascript
            $('#star-rate-#{review.id}').raty({
              size: 36,
              starOff:  '#{asset_path('star-off.png')}',
              starOn : '#{asset_path('star-on.png')}',
              starHalf: '#{asset_path('star-half.png')}',
              half: true,
              readOnly: true,
              score: #{review.rate},
            });
        .rate
          = review.rate
        .offset-md-5.col-md-5
          %p= review.content
          %p= review.user.name
          %label= l review.created_at
    - if user_signed_in?
      .row.mt-3
        .offset-md-5.col-md-7
          = form_with model: @review, url: product_reviews_path(@product) do |f|
            #star.form-group.row
              = f.label :rate,'評価', class:"col-md-3 col-form-label"
              = f.hidden_field :rate, id: :review_star
            :javascript
              $('#star').raty({
                size     : 36,
                starOff:  '#{asset_path('star-off.png')}',
                starOn : '#{asset_path('star-on.png')}',
                starHalf: '#{asset_path('star-half.png')}',
                scoreName: 'review[rate]',
                half: true,
              });
            = f.text_area :content, class: "form-control mb-2"
            = f.submit "レビューを追加" , class:"btn comment-button text-favorite w-100 mb-5 "

app/views/products/favorite.js.haml
$("#favorite-product").html("#{j(render partial: "products/favorite", locals: {product: @product})}");

app/views/products/index.html.haml
.main-visual
  = image_tag "image5.jpg", class: "main-image"
  %p.main-visual_title
    %i.fas.fa-coffee.coffe-icon
    AkoShop.

= render 'product'

app/views/products/show.html.haml
.d-flex.justify-content-center.content
  .row.w-75
    .col-md-4.mr-2
      - if @product.image.attached?
        = image_tag @product.image,class: "img-thumbnail product_image"
        %div{:class => add_active_class}
          %span.triangle
          - if @product.soldout_flag
            %span.label Sold
      - else
        = image_tag "salt.png", class: "img-thumbnail"
    .col-md-4
      .d-flex.flex-column
        .review_avg
          %h1= @product.name
          = link_to product_reviews_path(@product),class: "btn btn-outline-warning text-dark btn-sm ml-2"  do
            %div{:id => "star-rate-#{@product.id}"}
              Review #{@product.reviews.count}件  
              %br/
            :javascript
              $('#star-rate-#{@product.id}').raty({
                size: 36,
                starOff:  '#{asset_path('star-off.png')}',
                starOn : '#{asset_path('star-on.png')}',
                starHalf: '#{asset_path('star-half.png')}',
                half: true,
                readOnly: true,
                score: #{@product.reviews.average(:rate).to_f.round(1)},
              });
        %p.d-flex.align-items-end.item-price
          ￥#{@product.price.to_s(:delimited)}
          %span.ml-2 税込
      = form_with url: cart_create_users_path, local: true do |f|
        = f.hidden_field :product_id, value: @product.id
        = f.hidden_field :name, value: @product.name
        = f.hidden_field :price, value: @product.price
        .form-group.row
          = f.label "数量", class: "col-sm-2 col-form-label"
          .col-sm-10
            = f.number_field :quantity, min:1, value:1, class: "form-control w-25"
        .row
          - if user_signed_in?
            = render 'products/modal'
            - if @product.soldout_flag
              = link_to new_contact_path, class: 'btn btn-outline-dark btn-block mt-3' do
                %p 再入荷お知らせ
            - else
              = f.submit "カートに入れる", class: "btn btn-primary w-100 mb-2" do
                %i.fas.fa-shopping-cart
            = link_to favorite_product_path, class: "btn btn-outline-dark text-favorite mt-2 mb-5",remote: true do
              #favorite-product
                = render "products/favorite", product: @product
          - else
            = link_to new_user_session_path do
              %button.btn.btn-primary.w-100 ログインしてください
        .row
          %p= @product.description
          .tag
            - @product.tags.each do |tag|
              = link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect") ,class: "tag_name"
          = link_to new_contact_path, class: 'btn btn-outline-dark btn-block mt-3' do
            %i.fas.fa-envelope>
            アイテムについて問い合わせ
%hr/
%div
  .container
    %h3.title おすすめアイテム
    .row
      - @recommend_products.each do |recommend_product|
        .col-4.col-md-2.product-box
          = link_to product_path(recommend_product) do
            - if recommend_product.image.attached?
              = image_tag recommend_product.image, class: "img-thumbnail"
            - else
              = image_tag "salt.png", class: "img-thumbnail"
          .row
            .col-12
              %p.product-lavel.mt-2
                = recommend_product.name
                %label
                  ￥#{recommend_product.price.to_s(:delimited)}
= link_to  products_path  do
  %button.btn.btn-secondary.btn-lg.mx-auto.d-block 商品一覧に戻る